import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import React from "react";
import PropTypes from "prop-types";

// import { ToastContainer } from "react-toastify";
// import "react-toastify/dist/ReactToastify.css";
import Footer from "../../components/home/footer/footer";
import Navbar from "../../components/home/navbar/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ✅ Navbar */}
        <Navbar />

        {/* ✅ Main Content */}
        <main>{children}</main>

        {/* ✅ Footer */}
        <Footer />

        {/* ✅ Toast Notifications */}
        {/* <ToastContainer
          position="top-right"
          autoClose={4000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        /> */}
      </body>
    </html>
  );
}

RootLayout.propTypes = {
  children: PropTypes.node.isRequired,
};
